"""add campaigns, assessments, answers

Revision ID: 10dbd2913430
Revises: 5960019a04f6
Create Date: 2026-07-29 17:26:00.276177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dbd2913430'
down_revision: Union[str, Sequence[str], None] = '5960019a04f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='campaignstatus', native_enum=False, length=20), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='assessmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_assessments_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], name=op.f('fk_assessments_respondent_id_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], name=op.f('fk_assessments_subject_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments')),
    sa.UniqueConstraint('campaign_id', 'respondent_id', 'subject_id', name='uq_assessment_campaign_respondent_subject')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value BETWEEN 1 AND 5', name=op.f('ck_answers_answer_value_range')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_answers_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_answer_assessment_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('assessments')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
