"""Кейсы (профильные группы) + членство пользователя.

Членство выражено обычным FK users.case_id, а не association object'ом вроде
teacher_classes: и у ученика, и у учителя кейс РОВНО ОДИН (подтверждено
заказчиком), и «ровно один» надёжнее гарантировать схемой, чем проверкой в
сервисе. Одна колонка на обе роли — кто есть кто, различается по users.role.

Колонка nullable: «не состоит ни в каком кейсе» — штатное состояние
большинства пользователей, а не пропуск данных. Открепление участника
(DELETE /cases/{id}/members/{uid}) просто зануляет её, человек остаётся в
системе со всей историей.

Revision ID: 1bb952b43476
Revises: e7b3f9c2a815
Create Date: 2026-08-29 13:29:01.267918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb952b43476'
down_revision: Union[str, Sequence[str], None] = 'e7b3f9c2a815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('name', name=op.f('uq_cases_name'))
    )
    op.add_column('users', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_case_id_cases'), 'users', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_case_id_cases'), 'users', type_='foreignkey')
    op.drop_column('users', 'case_id')
    op.drop_table('cases')
    # ### end Alembic commands ###
