"""add school classes, teacher_classes and users.school_class_id

Revision ID: 2d37fc377820
Revises: 3909d9a917b9
Create Date: 2026-07-24 14:59:21.778856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d37fc377820'
down_revision: Union[str, Sequence[str], None] = '3909d9a917b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.CheckConstraint('grade BETWEEN 1 AND 11', name=op.f('ck_school_classes_grade_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_classes')),
    sa.UniqueConstraint('grade', 'section', name='uq_school_classes_grade_section')
    )
    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_teacher_classes_class_id_school_classes')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('teacher_id', 'class_id', name=op.f('pk_teacher_classes'))
    )
    op.add_column('users', sa.Column('school_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_school_class_id_school_classes'), 'users', 'school_classes', ['school_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_school_class_id_school_classes'), 'users', type_='foreignkey')
    op.drop_column('users', 'school_class_id')
    op.drop_table('teacher_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
