"""promotion_runs — журнал ежегодного перевода классов.

Одна строка на запуск перевода всей школы на класс вперёд. Партиальный
уникальный индекс по academic_year среди строк с undone_at IS NULL —
маркер «за этот учебный год перевод уже сделан»: второй активный запуск за
тот же год физически невозможен. snapshot (JSON) хранит класс и активность
каждого затронутого ученика ДО перевода — под откат.

Revision ID: 4e46f67fc4d3
Revises: c7a4f1d9e230
Create Date: 2026-09-07 14:33:22.522263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e46f67fc4d3'
down_revision: Union[str, Sequence[str], None] = 'c7a4f1d9e230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=False),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ran_by_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ran_by_id'], ['users.id'], name=op.f('fk_promotion_runs_ran_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_runs'))
    )
    op.create_index('uq_promotion_runs_active_year', 'promotion_runs', ['academic_year'], unique=True, postgresql_where=sa.text('undone_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_promotion_runs_active_year', table_name='promotion_runs', postgresql_where=sa.text('undone_at IS NULL'))
    op.drop_table('promotion_runs')
    # ### end Alembic commands ###
