"""add parent_children table and homeroom teacher

Revision ID: 5960019a04f6
Revises: 2d37fc377820
Create Date: 2026-07-28 19:14:56.794265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5960019a04f6'
down_revision: Union[str, Sequence[str], None] = '2d37fc377820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_children',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], name=op.f('fk_parent_children_child_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_children_parent_id_users')),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name=op.f('pk_parent_children'))
    )
    op.add_column('school_classes', sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_school_classes_homeroom_teacher_id_users'), 'school_classes', 'users', ['homeroom_teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_school_classes_homeroom_teacher_id_users'), 'school_classes', type_='foreignkey')
    op.drop_column('school_classes', 'homeroom_teacher_id')
    op.drop_table('parent_children')
    # ### end Alembic commands ###
